# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publishTime']},
        ),
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.CharField(default='/static/blog/img/headers/4.jpg', max_length=255, verbose_name='用户头像'),
        ),
    ]
