# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 07:55
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181009_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(default='static/img/img/headers/5.jpg', upload_to='static/img/img/headers/', verbose_name='用户头像'),
        ),
    ]
